### PR TITLE
Get basic bellows functionality working again

### PR DESCRIPTION
**Pull request by Klindel**
This allows you to add/update a track with youtube again.  It fixes play/stop functionality.  I have not tested playlist imports yet but the most important functionality is working again

### CODE REVIEW

**Comment by rbarkoch** [comment]
This seems to get the music working for the DM, but doesn't fix the music on the players end. Tested on V0.8.6

**Comment by Klindel** [comment]
thanks for pointing that out, I'll take a look

**Comment by casualchameleon** [comment]
Thanks @Klindel - this is a great basis for getting functionality back up and running.

**Comment by Klindel** [comment]
@casualchameleon I helped a tiny bit.  I'm looking at how to fix this for the non host account and it's a lot trickier.  It might require a lot of overrides unless I'm not understanding something. I think it all needs to start with PlaylistSound.sync as the first override

**Comment by casualchameleon** [comment]
@Klindel Yeah I've spent the last few hours going over the changes and the effects they've had on Bellows (yikes...). It looks like we want to go even deeper than that. The AudioContainer class contains a lot of the logic for playback now, so rather than patching Sound, PlaylistSound, etc. I think it would make sense to override AudioContainer's constructor and handle it that way. Sound.load(), Sound.play() etc. directly interact with that class.

I'm thinking along the lines of extending AudioContainer and implementing some logic in the Sound constructor to decide whether to use the OG AudioContainer or our StreamAudioContainer. 

The main issue with that is that the Sound class doesn't carry any information other than the src (which is 'invalid.mp3' for all streamed audio), so I think overriding the _createSound method and making that create a sound object with the metadata it needs to create the streamed audio player (youtube url etc.) is the way forward.

This is a lot of extra scaffolding work, but it definitely beats monkey patching all the methods that call the play function on sounds like you mentioned.

**Pull request merged**
